name       : perl-class-inspector
version    : '1.32'
release    : 4
source     :
    - http://search.cpan.org/CPAN/authors/id/P/PL/PLICEASE/Class-Inspector-1.32.tar.gz : cefadc8b5338e43e570bc43f583e7c98d535c17b196bcf9084bb41d561cc0535
license    : Artistic-2.0
component  : programming.perl
summary    : Get information about a class and its structure
description: |
    Get information about a class and its structure
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
