name       : perl-class-inspector
version    : '1.36'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/Class-Inspector-1.36.tar.gz : cc295d23a472687c24489d58226ead23b9fdc2588e522f0b5f0747741700694e
license    : Artistic-2.0
component  : programming.perl
summary    : Get information about a class and its structure
description: |
    Get information about a class and its structure
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
