name       : perl-class-inspector
version    : 1.31
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/P/PL/PLICEASE/Class-Inspector-1.31.tar.gz : 065f649f1f7a676f0496c37dc155cf4812edb77bdbb0e95d28c985deff930eeb
license    : Artistic-2.0
component  : programming.perl
summary    : Get information about a class and its structure
description: |
    Get information about a class and its structure
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
